repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.3.0
    hooks:
    -   id: check-docstring-first
        stages:
        - commit
        - push
    -   id: check-merge-conflict
        stages:
        - push
    -   id: double-quote-string-fixer
        stages:
        - commit
        - push
-   repo: https://gitlab.com/pycqa/flake8
    rev: 3.8.4
    hooks:
    -   id: flake8
        args: [--max-line-length=120]
        exclude: (^src/panel/migrations/|^nginx/)
        stages:
        - commit
        - push
-   repo: https://github.com/pre-commit/mirrors-autopep8
    rev: v1.5.4
    hooks:
    -   id: autopep8
        args: [--in-place, --max-line-length=120]
        exclude: (^src/panel/migrations/|^nginx/)
        stages:
        - commit
        - push
