version: '3.7'

volumes:
  postgres_data:

services:
  web:
    build: ./django
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./django/:/usr/src/app/
    ports:
      - 8000:8000
    env_file:
      - .env.example
    depends_on:
      - db

  db:
    image: postgres:13.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=hello_django
      - POSTGRES_PASSWORD=hello_django
      - POSTGRES_DB=hello_django_dev
    ports:
      - 5432:5432

  redis:
    image: redis:6.0.8-alpine

  celery-embed-worker:
    build: ./django
    command: celery -A project worker -l info
    volumes:
      - ./django/:/usr/src/app/
    env_file:
      - ./.env.example
    depends_on:
      - db
      - redis
