# Generated by Django 3.2.4 on 2021-06-15 22:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Computation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=126, null=True)),
                ('status', models.CharField(choices=[
                 ('pending', 'In a queue'), ('running', 'Currently running'), ('completed', 'Completed')], default='pending', max_length=9)),
                ('started', models.DateTimeField(blank=True, null=True)),
                ('ended', models.DateTimeField(blank=True, null=True)),
                ('date_start', models.DateField()),
                ('date_fin', models.DateField()),
                ('lag', models.IntegerField()),
            ],
            options={
                'ordering': ['-started'],
            },
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('liquid', models.FloatField()),
                ('oil', models.FloatField()),
                ('water', models.FloatField()),
                ('wct', models.FloatField()),
                ('computation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                                  related_name='results', to='well_feature_generator.computation')),
            ],
        ),
    ]
